<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
	'acceptable_sugar_versions' => 
		array (
		  'regex_matches' => array (
		      0 => '6\\.5\\.(.*?)',
		    ),
		),
	'acceptable_sugar_flavors' => 
		array (
		  0 => 'CE',
		),
	'readme' => 'Tabbed Subpanels',
	'key' => 'TABS',
	'author' => 'Brian Lasher (me@brianlasher.com)',
	'description' => 'Tab Subpanels',
	'icon' => '',
	'is_uninstallable' => true,
	'name' => 'Tabbed Subpanels for SuiteCRM',
	'published_date' => '2016-05-06 15:31:00',
	'type' => 'module',
	'class' => 'Tabbed_Subpanels',
	'version' => '1.0.00',
	'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'TabbedSubpanels'
);


$installdefs['copy'] = array(
	0 => array(
		'from' => '<basepath>/files/custom/Extension/application/Ext/LogicHooks/tabbed_subpanels_hook.php',
		'to' => 'custom/Extension/application/Ext/LogicHooks/tabbed_subpanels_hook.php',
	) ,
	1 => array(
		'from' => '<basepath>/files/custom/Extension/application/tabbed_subpanels/tabbed_subpanels.php',
		'to' => 'custom/Extension/application/tabbed_subpanels/tabbed_subpanels.php',
	) ,
	2 => array(
		'from' => '<basepath>/files/custom/Extension/application/tabbed_subpanels/tabbed_subpanels.js',
		'to' => 'custom/Extension/application/tabbed_subpanels/tabbed_subpanels.js',
	) ,
	3 => array(
		'from' => '<basepath>/files/custom/Extension/application/tabbed_subpanels/tabbed_subpanels_css.php',
		'to' => 'custom/Extension/application/tabbed_subpanels/tabbed_subpanels_css.php',
	) ,
);